In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('train.csv')
df.head()

id Product ID Type  Air temperature [K]  Process temperature [K]  \
0   0     L50096    L                300.6                    309.6   
1   1     M20343    M                302.6                    312.1   
2   2     L49454    L                299.3                    308.5   
3   3     L53355    L                301.0                    310.9   
4   4     M24050    M                298.0                    309.0   

   Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Machine failure  TWF  \
0                    1596         36.1              140                0    0   
1                    1759         29.1              200                0    0   
2                    1805         26.5               25                0    0   
3                    1524         44.3              197                0    0   
4                    1641         35.4               34                0    0   

   HDF  PWF  OSF  RNF  
0    0    0    0    0  
1    0    0    0    0  
2    0    0    0    0  
3    0    0    0    0  
4    0    0    0    0

In [5]:
df = df.drop(['id', 'Product ID'], axis=1)

In [6]:
set(df['Type'])
# l - 0
# m - 1
# h - 2

{'H', 'L', 'M'}

In [7]:
def typeMapping(t):
    if t == 'L': return 0
    elif t == 'M': return 1
    else: return 2

In [8]:
df.head()
df['Type'] = df['Type'].map(typeMapping)

In [9]:
# df.dropna(inplace=True)
# df.head()
# df.tail()

In [10]:
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
import numpy as np

In [11]:
X = np.array(df.drop(['Machine failure'], axis=1))
y = np.array(df['Machine failure'])

In [12]:
X = preprocessing.scale(X)

df.dropna(inplace=True)
y = np.array(df['Machine failure'])

In [13]:
df.head()

Type  Air temperature [K]  Process temperature [K]  Rotational speed [rpm]  \
0     0                300.6                    309.6                    1596   
1     1                302.6                    312.1                    1759   
2     0                299.3                    308.5                    1805   
3     0                301.0                    310.9                    1524   
4     1                298.0                    309.0                    1641   

   Torque [Nm]  Tool wear [min]  Machine failure  TWF  HDF  PWF  OSF  RNF  
0         36.1              140                0    0    0    0    0    0  
1         29.1              200                0    0    0    0    0    0  
2         26.5               25                0    0    0    0    0    0  
3         44.3              197                0    0    0    0    0    0  
4         35.4               34                0    0    0    0    0    0

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [15]:
clf = svm.SVC()
clf.fit(X_train, y_train)

SVC()

In [16]:
accuracy = clf.score(X_test, y_test)
accuracy

0.9967016052187935

## Training on 100% data

In [17]:
X = np.array(df.drop(['Machine failure'], axis=1))
df.dropna(inplace=True)
y = np.array(df['Machine failure'])
df.head()

Type  Air temperature [K]  Process temperature [K]  Rotational speed [rpm]  \
0     0                300.6                    309.6                    1596   
1     1                302.6                    312.1                    1759   
2     0                299.3                    308.5                    1805   
3     0                301.0                    310.9                    1524   
4     1                298.0                    309.0                    1641   

   Torque [Nm]  Tool wear [min]  Machine failure  TWF  HDF  PWF  OSF  RNF  
0         36.1              140                0    0    0    0    0    0  
1         29.1              200                0    0    0    0    0    0  
2         26.5               25                0    0    0    0    0    0  
3         44.3              197                0    0    0    0    0    0  
4         35.4               34                0    0    0    0    0    0

In [18]:
clf = svm.SVR()
clf.fit(X, y)

In [ ]:
test_df = pd.read_csv('test.csv')
test_df.head()

id Product ID Type  Air temperature [K]  Process temperature [K]  \
0  136429     L50896    L                302.3                    311.5   
1  136430     L53866    L                301.7                    311.0   
2  136431     L50498    L                301.3                    310.4   
3  136432     M21232    M                300.1                    309.6   
4  136433     M19751    M                303.4                    312.3   

   Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  TWF  HDF  PWF  OSF  \
0                    1499         38.0               60    0    0    0    0   
1                    1713         28.8               17    0    0    0    0   
2                    1525         37.7               96    0    0    0    0   
3                    1479         47.6                5    0    0    0    0   
4                    1515         41.3              114    0    0    0    0   

   RNF  
0    0  
1    0  
2    0  
3    0  
4    0

In [ ]:
test_df['Type'] = test_df['Type'].map(typeMapping)

In [ ]:
predictions = clf.predict(np.array(test_df.drop(['id', 'Product ID'], axis=1)))

In [ ]:
predictions

array([0.09944059, 0.08527317, 0.09907215, ..., 0.10000712, 0.09863869,
       0.09883733])

In [ ]:
test_df.head()

id Product ID  Type  Air temperature [K]  Process temperature [K]  \
0  136429     L50896     0                302.3                    311.5   
1  136430     L53866     0                301.7                    311.0   
2  136431     L50498     0                301.3                    310.4   
3  136432     M21232     1                300.1                    309.6   
4  136433     M19751     1                303.4                    312.3   

   Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  TWF  HDF  PWF  OSF  \
0                    1499         38.0               60    0    0    0    0   
1                    1713         28.8               17    0    0    0    0   
2                    1525         37.7               96    0    0    0    0   
3                    1479         47.6                5    0    0    0    0   
4                    1515         41.3              114    0    0    0    0   

   RNF  
0    0  
1    0  
2    0  
3    0  
4    0

In [ ]:
test_df['Machine failure'] = predictions

In [ ]:
test_df.head()

id Product ID  Type  Air temperature [K]  Process temperature [K]  \
0  136429     L50896     0                302.3                    311.5   
1  136430     L53866     0                301.7                    311.0   
2  136431     L50498     0                301.3                    310.4   
3  136432     M21232     1                300.1                    309.6   
4  136433     M19751     1                303.4                    312.3   

   Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  TWF  HDF  PWF  OSF  \
0                    1499         38.0               60    0    0    0    0   
1                    1713         28.8               17    0    0    0    0   
2                    1525         37.7               96    0    0    0    0   
3                    1479         47.6                5    0    0    0    0   
4                    1515         41.3              114    0    0    0    0   

   RNF  Machine failure  
0    0         0.099441  
1    0         0.085273  
2    0         0.099072  
3    0         0.099740  
4    0         0.099387

In [ ]:
submission = test_df.filter(['id', 'Machine failure'], axis=1)

In [ ]:
submission

id  Machine failure
0      136429         0.099441
1      136430         0.085273
2      136431         0.099072
3      136432         0.099740
4      136433         0.099387
...       ...              ...
90949  227378         0.099669
90950  227379         0.098117
90951  227380         0.100007
90952  227381         0.098639
90953  227382         0.098837

[90954 rows x 2 columns]

In [ ]:
ss = pd.read_csv('sample_submission.csv')
ss

id  Machine failure
0      136429              0.5
1      136430              0.5
2      136431              0.5
3      136432              0.5
4      136433              0.5
...       ...              ...
90949  227378              0.5
90950  227379              0.5
90951  227380              0.5
90952  227381              0.5
90953  227382              0.5

[90954 rows x 2 columns]

In [ ]:
submission.to_csv('kaggle_machine_failure_pred_1.csv')

In [ ]:
submission.head()

id  Machine failure
0  136429         0.099441
1  136430         0.085273
2  136431         0.099072
3  136432         0.099740
4  136433         0.099387

## Using linear regression

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
clf = LinearRegression()

In [ ]:
X = np.array(df.drop(['Machine failure'], axis=1))
df.dropna(inplace=True)
y = np.array(df['Machine failure'])
df.head()

Type  Air temperature [K]  Process temperature [K]  Rotational speed [rpm]  \
0     0                300.6                    309.6                    1596   
1     1                302.6                    312.1                    1759   
2     0                299.3                    308.5                    1805   
3     0                301.0                    310.9                    1524   
4     1                298.0                    309.0                    1641   

   Torque [Nm]  Tool wear [min]  Machine failure  TWF  HDF  PWF  OSF  RNF  
0         36.1              140                0    0    0    0    0    0  
1         29.1              200                0    0    0    0    0    0  
2         26.5               25                0    0    0    0    0    0  
3         44.3              197                0    0    0    0    0    0  
4         35.4               34                0    0    0    0    0    0

In [ ]:
X
y

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
clf.fit(X, y)

LinearRegression()

In [ ]:
test_df = pd.read_csv('test.csv')
test_df.head()

id Product ID Type  Air temperature [K]  Process temperature [K]  \
0  136429     L50896    L                302.3                    311.5   
1  136430     L53866    L                301.7                    311.0   
2  136431     L50498    L                301.3                    310.4   
3  136432     M21232    M                300.1                    309.6   
4  136433     M19751    M                303.4                    312.3   

   Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  TWF  HDF  PWF  OSF  \
0                    1499         38.0               60    0    0    0    0   
1                    1713         28.8               17    0    0    0    0   
2                    1525         37.7               96    0    0    0    0   
3                    1479         47.6                5    0    0    0    0   
4                    1515         41.3              114    0    0    0    0   

   RNF  
0    0  
1    0  
2    0  
3    0  
4    0

In [ ]:
id = test_df['id']
id

0        136429
1        136430
2        136431
3        136432
4        136433
          ...  
90949    227378
90950    227379
90951    227380
90952    227381
90953    227382
Name: id, Length: 90954, dtype: int64

In [ ]:
test_df['Type'] = test_df['Type'].map(typeMapping)
predictions = clf.predict(np.array(test_df.drop(['id', 'Product ID'], axis=1)))

In [ ]:
predictions

array([1.70389163e-03, 7.96545548e-05, 2.76605507e-03, ...,
       3.81262796e-03, 3.51420867e-03, 1.98522894e-03])

In [ ]:
test_df['Machine failure'] = predictions

In [ ]:
test_df.head()

id Product ID  Type  Air temperature [K]  Process temperature [K]  \
0  136429     L50896     2                302.3                    311.5   
1  136430     L53866     2                301.7                    311.0   
2  136431     L50498     2                301.3                    310.4   
3  136432     M21232     2                300.1                    309.6   
4  136433     M19751     2                303.4                    312.3   

   Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  TWF  HDF  PWF  OSF  \
0                    1499         38.0               60    0    0    0    0   
1                    1713         28.8               17    0    0    0    0   
2                    1525         37.7               96    0    0    0    0   
3                    1479         47.6                5    0    0    0    0   
4                    1515         41.3              114    0    0    0    0   

   RNF  Machine failure  
0    0         0.001704  
1    0         0.000080  
2    0         0.002766  
3    0         0.007596  
4    0         0.006553

In [ ]:
test_df.filter(['id', 'Machine failure']).to_csv('2_kaggle_machine_failure_pred.csv', index=False)

## Using kernal ridge regression

In [ ]:
from sklearn.kernel_ridge import KernelRidge
clf = KernelRidge(alpha=1.0)

In [ ]:
X = np.array(df.drop(['Machine failure'], axis=1))
df.dropna(inplace=True)
y = np.array(df['Machine failure'])
df.head()

NameError: name 'np' is not defined

In [ ]:
clf.fit(X, y)

: 

: 